{% set version = "1.0.2" %}

package:
  name: morphometrix 
  version: {{ version }} 

source:
  git_url: https://github.com/wingtorres/morphometrix/
  #url: https://github.com/simplejson/simplejson/releases/download/{{ version }}/simplejson-{{ version }}.tar.gz

build:
  noarch: python
  number: 0
  script: python setup.py install #python -m pip install #--no-deps --ignore-installed  # 

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - pyside6 >=6.5.0
    - scipy >= 1.9.1
    
about:
  home: https://github.com/wingtorres/morphometrix/
  license: MIT
  summary: A GUI for photogrammetry
