
package:
  name: morphometrix 
  version: "1.0.2"

source:
  #path: morphometrix/
  git_url: https://github.com/wingtorres/morphometrix/

build:
  noarch: python
  number: '0'
  script: python setup.py install #python -m pip install #--no-deps --ignore-installed  # 

requirements:
  build:
    - python 
  
  run:
    - python
    - numpy
    - pyqt
    
about:
  home: https://github.com/wingtorres/morphometrix/
  license: MIT
  summary: A GUI for photogrammetry
